### ISSUE TITLE
Kibana Elastic Search Installation

### ISSUE THREAD

**Issue by DiptoChakrabarty** [CodeChefVIT/Secondary-Domain-Tasks-20#8]
Create Docker file to install Kibana and Elastic search and write down relevant steps to deploy in local system and use them

**Comment by rav94** [comment]
Can this be a docker-compose file instead of a Dockerfile

**Comment by DiptoChakrabarty** [comment]
Sure will work @rav94

**Comment by rav94** [comment]
@DiptoChakrabarty thanks for the clarification. Added the PR
